In [490]:
import numpy as np
from scipy import signal, io
import matplotlib.pyplot as plt
from acquisition_tools import cal_matrix, estimate_rpm
from tkinter import Tk
from tkinter.filedialog import askopenfilename
%matplotlib qt

plt.rcParams['text.usetex'] = False
plt.rcParams['font.family'] = 'serif'
plt.rcParams['font.serif'] = 'Times New Roman'
plt.rcParams['font.size'] = 16

cal_mat = cal_matrix()

In [519]:
# Load the .mat file
# Open a file dialog to choose a .mat file
root = Tk()
# root.withdraw()  # Hide the main window
file_path = askopenfilename(initialdir='./results', filetypes=[("MAT files", "*.mat")])
root.destroy()  # Destroy the main window

exp_data = io.loadmat(file_path)

In [520]:
time = exp_data['t']
fs_analog = exp_data['Fs_analog'].flatten()[0]
station_time = exp_data['station_time'].flatten()[0]

diameter_in = exp_data['D_inch']
pitch_in = exp_data['pitch']

diameter_m = diameter_in * 0.0254
pitch_m = pitch_in * 0.0254

rho = exp_data['rho']

voltage = exp_data['data']
force_net = exp_data['force_net']
force_raw = exp_data['force']
t_analog = np.linspace(0, len(force_raw)/fs_analog, len(force_raw)).flatten()

z_pulse = voltage[:, 6]
z_pulse = np.where(z_pulse > 1, 5, z_pulse)

rpm_sweep = exp_data['rpm_sweep'].flatten()
U_inf = exp_data['U_inf'].flatten()
rpm_command = exp_data['rpm_command'].flatten()

In [521]:
mano_data = exp_data['data_mano']
u = ((mano_data[:, 1] * 200 * 2 / (rho))**0.5).flatten()
time_u = np.linspace(0, time.max(), len(u))

plt.figure(figsize=(10, 5))
plt.plot(time_u, u, label='Velocity (u)', color='blue')
plt.xlabel('Time [s]')
plt.ylabel('Velocity [m/s]')
plt.title('Velocity (u) as a function of Time')
plt.legend()
plt.grid()
plt.show()

In [522]:
indices = np.where(np.diff(z_pulse) > 1)[0]
rpm = 60/np.diff(t_analog.flatten()[indices])
t_rpm = t_analog.flatten()[indices[:-1]]

In [523]:
time_diffs = np.diff(time.flatten())
mean_fs = 1 / np.mean(time_diffs)
print(mean_fs)

19.99433811899611


In [524]:
# Resample rpm to match fs_analog
num_samples = int(len(t_analog))
rpm_resampled = signal.resample(rpm, num_samples)
rpm_command_resampled = signal.resample(rpm_command, num_samples)
u_resampled = signal.resample(u, num_samples)

In [109]:
fig, axes = plt.subplots(2, 3, figsize=(15, 10))

axes[0, 0].plot(t_analog, voltage[:, 0], "-")
axes[0, 0].set_xlabel("Time [s]")
axes[0, 0].set_ylabel("$F_x$ [N]")
axes[0, 0].grid()

axes[0, 1].plot(t_analog, voltage[:, 1], "-")
axes[0, 1].set_xlabel("Time [s]")
axes[0, 1].set_ylabel("$F_y$ [N]")
axes[0, 1].grid()

axes[0, 2].plot(t_analog, voltage[:, 2], "-")
axes[0, 2].set_xlabel("Time [s]")
axes[0, 2].set_ylabel("$F_z$ [N]")
axes[0, 2].grid()

axes[1, 0].plot(t_analog, voltage[:, 3], "-")
axes[1, 0].set_xlabel("Time [s]")
axes[1, 0].set_ylabel("$T_x$ [N]")
axes[1, 0].grid()

axes[1, 1].plot(t_analog, voltage[:, 4], "-")
axes[1, 1].set_xlabel("Time [s]")
axes[1, 1].set_ylabel("$T_y$ [N]")
axes[1, 1].grid()

axes[1, 2].plot(t_analog, voltage[:, 5], "-")
axes[1, 2].set_xlabel("Time [s]")
axes[1, 2].set_ylabel("$T_z$ [N]")
axes[1, 2].grid()

plt.tight_layout()
plt.show()

In [484]:
fig, axes = plt.subplots(2, 3, figsize=(15, 10))

axes[0, 0].plot(t_analog, force_raw[:, 0], "-")
axes[0, 0].set_xlabel("Time [s]")
axes[0, 0].set_ylabel("$F_x$ [N]")
axes[0, 0].grid()

axes[0, 1].plot(t_analog, force_raw[:, 1], "-")
axes[0, 1].set_xlabel("Time [s]")
axes[0, 1].set_ylabel("$F_y$ [N]")
axes[0, 1].grid()

axes[0, 2].plot(t_analog, force_raw[:, 2], "-")
axes[0, 2].set_xlabel("Time [s]")
axes[0, 2].set_ylabel("$F_z$ [N]")
axes[0, 2].grid()

axes[1, 0].plot(t_analog, force_raw[:, 3], "-")
axes[1, 0].set_xlabel("Time [s]")
axes[1, 0].set_ylabel("$T_x$ [N]")
axes[1, 0].grid()

axes[1, 1].plot(t_analog, force_raw[:, 4], "-")
axes[1, 1].set_xlabel("Time [s]")
axes[1, 1].set_ylabel("$T_y$ [N]")
axes[1, 1].grid()

axes[1, 2].plot(t_analog, force_raw[:, 5], "-")
axes[1, 2].set_xlabel("Time [s]")
axes[1, 2].set_ylabel("$T_z$ [N]")
axes[1, 2].grid()

plt.tight_layout()
plt.show()

In [525]:
dt = 1/fs_analog
order = 2
cutoff = 5
nyq = 0.5 * fs_analog
normal_cutoff = cutoff / nyq

b, a = signal.butter(order, normal_cutoff)
z_l = z_d = signal.lfilter_zi(b, a)

Fz_raw = force_net[:, 2]
Tz_raw = force_net[:, 5]

Fx = signal.lfilter(b, a, force_net[:, 0], zi=z_l)[0]
Fy = signal.lfilter(b, a, force_net[:, 1], zi=z_l)[0]
Fz = signal.lfilter(b, a, force_net[:, 2], zi=z_l)[0]
Tx = signal.lfilter(b, a, force_net[:, 3], zi=z_l)[0]
Ty = signal.lfilter(b, a, force_net[:, 4], zi=z_l)[0]
Tz = signal.lfilter(b, a, force_net[:, 5], zi=z_l)[0]

In [334]:
fig, axes = plt.subplots(2, 3, figsize=(15, 10))

axes[0, 0].plot(t_analog, Fx, "-")
axes[0, 0].set_xlabel("Time [s]")
axes[0, 0].set_ylabel("$F_x$ [N]")
axes[0, 0].grid()

axes[0, 1].plot(t_analog, Fy, "-")
axes[0, 1].set_xlabel("Time [s]")
axes[0, 1].set_ylabel("$F_y$ [N]")
axes[0, 1].grid()

axes[0, 2].plot(t_analog, Fz, "-")
axes[0, 2].set_xlabel("Time [s]")
axes[0, 2].set_ylabel("$F_z$ [N]")
axes[0, 2].grid()

axes[1, 0].plot(t_analog, Tx, "-")
axes[1, 0].set_xlabel("Time [s]")
axes[1, 0].set_ylabel("$T_x$ [N]")
axes[1, 0].grid()

axes[1, 1].plot(t_analog, Ty, "-")
axes[1, 1].set_xlabel("Time [s]")
axes[1, 1].set_ylabel("$T_y$ [N]")
axes[1, 1].grid()

axes[1, 2].plot(t_analog, -Tz, "-")
axes[1, 2].set_xlabel("Time [s]")
axes[1, 2].set_ylabel("$T_z$ [N]")
axes[1, 2].grid()

plt.tight_layout()
plt.show()

Windowing

In [526]:
window_size = station_time  # window size in seconds
samples_per_window = int(window_size * fs_analog)  # number of samples per window

# Partition data and t_analog into 40-second windows
t_analog_windows = [t_analog[i:i + samples_per_window] for i in range(0, len(t_analog), samples_per_window) if i + samples_per_window <= len(t_analog)]
Fz_windows = [Fz_raw[i:i + samples_per_window] for i in range(0, len(Fz_raw), samples_per_window) if i + samples_per_window <= len(Fz_raw)]
Tz_windows = [Tz_raw[i:i + samples_per_window] for i in range(0, len(Tz_raw), samples_per_window) if i + samples_per_window <= len(Tz_raw)]
rpm_windows = [rpm_resampled[i:i + samples_per_window] for i in range(0, len(rpm_resampled), samples_per_window) if i + samples_per_window <= len(rpm_resampled)]
u_windows = [u_resampled[i:i + samples_per_window] for i in range(0, len(u_resampled), samples_per_window) if i + samples_per_window <= len(u_resampled)]


# Calculate the mean of each window, leaving out the first 10 seconds and the last 2 seconds
mean_Fz_windows = np.array([np.mean(window[int(10 * fs_analog):-int(2 * fs_analog)]) for window in Fz_windows])
mean_Tz_windows = np.array([np.mean(window[int(10 * fs_analog):-int(2 * fs_analog)]) for window in Tz_windows])
mean_rpm_windows = np.array([np.mean(window[int(10 * fs_analog):-int(2 * fs_analog)]) for window in rpm_windows])
mean_u_windows = np.array([np.mean(window[int(10 * fs_analog):-int(2 * fs_analog)]) for window in u_windows])
mean_n_windows = np.array(mean_rpm_windows) / 60

# Print the mean values of each window
print(mean_rpm_windows)
print(mean_Fz_windows)
print(mean_Tz_windows)
print(mean_u_windows)

[4508.4997555  4979.45998372 5489.66650088 6024.88291901 6535.59502277
 7085.54951793]
[2.97352374 3.61274506 4.30378706 5.31905377 6.72323319 8.72308387]
[-0.10792488 -0.12633904 -0.15089693 -0.18377269 -0.22888753 -0.28124025]
[6.09252064 6.03215005 6.03427274 6.04566826 6.06451724 6.10270784]


In [527]:
J = mean_u_windows / (mean_n_windows * diameter_m)
CT = mean_Fz_windows / (rho * mean_n_windows**2 * diameter_m**4)
CQ = -np.array(mean_Tz_windows) / (rho * mean_n_windows**2 * diameter_m**5)
CP = CQ * 2 * np.pi
eta = J * CT / CP

print(J)

[[0.31921441 0.28615901 0.25965489 0.23703541 0.21919399 0.20345416]]


In [528]:
# Create a figure and two subplots
fig, (ax1, ax2, ax3) = plt.subplots(1, 3, figsize=(16, 5))

# First subplot
ax1.plot(J, CT, label='Laminar', color='black', marker='o', linewidth = 2.5)
ax1.grid()
ax1.set_xlabel('J')
ax1.set_ylabel('$C_T$')
ax1.set_xlim(0.2, .8)
ax1.set_ylim(0, 0.15)
ax1.set_xticks(np.arange(0.2, .8, 0.1))
# ax1.legend(loc = 'lower left')

# Second subplot
ax2.plot(J, CP, label='Laminar', color='black', marker='o', linewidth = 2.5)
ax2.set_xlim(0.2, .8)
ax2.set_ylim(0., 0.1)
ax2.set_xlabel('J')
ax2.set_ylabel('$C_P$')
ax2.set_xticks(np.arange(0.2, .8, 0.1))
ax2.grid()

# Third subplot
ax3.plot(J, eta, label='Laminar', color='black', marker='o', linewidth = 2.5)
ax3.set_xlim(0.2, .8)
ax3.set_ylim(0, 1)
ax3.set_xlabel('J')
ax3.set_ylabel('$\eta$')
ax3.set_xticks(np.arange(0.2, .8, 0.1))
ax3.grid()

# Show the plot
plt.tight_layout()
plt.show()

<>:28: SyntaxWarning: invalid escape sequence '\e'
<>:28: SyntaxWarning: invalid escape sequence '\e'
C:\Users\Lab7\AppData\Local\Temp\ipykernel_26044\1759858291.py:28: SyntaxWarning: invalid escape sequence '\e'
  ax3.set_ylabel('$\eta$')


In [502]:
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 5))

# First subplot
ax1.plot(t_analog, Fz, "-", label='Thrust', linewidth = 2, color='k')
ax1.set_ylim(-20, 20)

for i, window in enumerate(Fz_windows):
    start_time = t_analog_windows[i][int(10 * fs_analog)]
    end_time = t_analog_windows[i][-1]
    ax1.axvspan(start_time, end_time, color='gray', alpha=0.3)
    ax2.axvspan(start_time, end_time, color='gray', alpha=0.3)

ax1_twiny = ax1.twinx()
ax1_twiny.plot(t_rpm, rpm, "-", label='RPM', linewidth=2, color='blue')
ax1_twiny.set_ylabel("RPM")

ax1_twiny.plot(t_analog, rpm_command_resampled, "-", label='RPM Command', linewidth=1, color='red')
ax1_twiny.set_ylabel("RPM Command")

lines, labels = ax1.get_legend_handles_labels()
lines2, labels2 = ax1_twiny.get_legend_handles_labels()
ax1_twiny.legend(lines + lines2, labels + labels2, loc='lower left')

ax1.set_xlabel("Time [s]")
ax1.set_ylabel("T [N]")
ax1.grid()

# Second subplot
ax2.plot(t_analog, -Tz, "-", label='Torque', linewidth = 2, color='red')
ax2.set_xlabel("Time [s]")
ax2.set_ylabel("Q [N.m]")
ax2.set_ylim(-0.5, 0.5)
ax2.legend()
ax2.grid()

plt.tight_layout()
plt.show()

C:\Users\Lab7\AppData\Local\Temp\ipykernel_26044\1552548930.py:36: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  plt.tight_layout()
